package codegen

const tsSDKTemplate = `// Code generated by msggen. DO NOT EDIT.

// ============================================================
// Message Interfaces
// ============================================================
{{- range .}}

/** {{.Comment}} */
export interface {{.Name}} {
{{- range .Fields}}
  {{.JSONName}}: {{tsType .Type}};
{{- end}}
}
{{- end}}

// ============================================================
// Message IDs & Names
// ============================================================

export const MessageIDs = {
{{- range .}}
  {{.Name}}: {{.ID}},
{{- end}}
} as const;

export type MessageType = keyof typeof MessageIDs;

const MessageNames: Record<number, string> = {
{{- range .}}
  {{.ID}}: "{{.Name}}",
{{- end}}
};

// ============================================================
// Type-Safe Message Map
// ============================================================

export interface MessageMap {
{{- range .}}
  {{.Name}}: {{.Name}};
{{- end}}
}

// ============================================================
// Client Options & Events
// ============================================================

export interface ClientOptions {
  /** WebSocket server URL, e.g. "ws://localhost:8080/ws" */
  url: string;
  /** Enable auto-reconnect (default: true) */
  reconnect?: boolean;
  /** Reconnect interval in ms (default: 3000) */
  reconnectInterval?: number;
  /** Max reconnect attempts, 0 = unlimited (default: 10) */
  maxReconnectAttempts?: number;
  /** Heartbeat ping interval in ms, 0 = disabled (default: 30000) */
  heartbeatInterval?: number;
  /** Protocol version for handshake (default: 1) */
  protocolVersion?: number;
}

export type MessageHandler<T> = (msg: T) => void;
export type ConnectHandler = () => void;
export type DisconnectHandler = (code: number, reason: string) => void;
export type ErrorHandler = (error: Event) => void;

// ============================================================
// Game Client SDK
// ============================================================

const PROTOCOL_VERSION = 1;
const SDK_VERSION = "1.0.0";

export class GameClient {
  private ws: WebSocket | null = null;
  private handlers = new Map<string, Set<Function>>();
  private connectHandlers = new Set<ConnectHandler>();
  private disconnectHandlers = new Set<DisconnectHandler>();
  private errorHandlers = new Set<ErrorHandler>();
  private options: Required<ClientOptions>;
  private reconnectAttempts = 0;
  private reconnectTimer: ReturnType<typeof setTimeout> | null = null;
  private heartbeatTimer: ReturnType<typeof setInterval> | null = null;
  private closed = false;
  private negotiatedVersion = PROTOCOL_VERSION;

  constructor(options: ClientOptions) {
    this.options = {
      url: options.url,
      reconnect: options.reconnect ?? true,
      reconnectInterval: options.reconnectInterval ?? 3000,
      maxReconnectAttempts: options.maxReconnectAttempts ?? 10,
      heartbeatInterval: options.heartbeatInterval ?? 30000,
      protocolVersion: options.protocolVersion ?? PROTOCOL_VERSION,
    };
  }

  /** Connect to the server with optional handshake */
  connect(): Promise<void> {
    this.closed = false;
    return new Promise((resolve, reject) => {
      try {
        this.ws = new WebSocket(this.options.url);
      } catch (err) {
        reject(err);
        return;
      }

      this.ws.onopen = () => {
        this.reconnectAttempts = 0;
        this.startHeartbeat();
        // Send handshake
        this.sendRaw({
          type: "__handshake__",
          protocol_version: this.options.protocolVersion,
          client_sdk: "ts-" + SDK_VERSION,
          supported_versions: [1],
        });
      };

      this.ws.onmessage = (event: MessageEvent) => {
        let data: any;
        try {
          data = JSON.parse(typeof event.data === "string" ? event.data : new TextDecoder().decode(event.data));
        } catch {
          return;
        }

        // Handle handshake response
        if (data.type === "__handshake_ack__") {
          if (data.status === "ok") {
            this.negotiatedVersion = data.protocol_version ?? PROTOCOL_VERSION;
            this.connectHandlers.forEach((h) => h());
            resolve();
          } else {
            reject(new Error(data.message ?? "handshake failed"));
          }
          return;
        }

        this.handleMessage(data);
      };

      this.ws.onerror = (event: Event) => {
        this.errorHandlers.forEach((h) => h(event));
        reject(event);
      };

      this.ws.onclose = (event: CloseEvent) => {
        this.stopHeartbeat();
        this.disconnectHandlers.forEach((h) => h(event.code, event.reason));
        if (!this.closed && this.options.reconnect) {
          this.tryReconnect();
        }
      };
    });
  }

  /** Disconnect from the server */
  disconnect(): void {
    this.closed = true;
    this.stopHeartbeat();
    if (this.reconnectTimer) {
      clearTimeout(this.reconnectTimer);
      this.reconnectTimer = null;
    }
    if (this.ws) {
      this.ws.close(1000, "client disconnect");
      this.ws = null;
    }
  }

  /** Get the negotiated protocol version */
  get protocolVersion(): number {
    return this.negotiatedVersion;
  }

  /** Check if connected */
  get connected(): boolean {
    return this.ws?.readyState === WebSocket.OPEN;
  }

  /** Send a typed message to the server */
  send<K extends keyof MessageMap>(type: K, msg: MessageMap[K]): void {
    this.sendRaw({ type, ...msg });
  }

  /** Register a handler for a message type */
  on<K extends keyof MessageMap>(type: K, handler: MessageHandler<MessageMap[K]>): void {
    if (!this.handlers.has(type as string)) {
      this.handlers.set(type as string, new Set());
    }
    this.handlers.get(type as string)!.add(handler);
  }

  /** Remove a handler for a message type */
  off<K extends keyof MessageMap>(type: K, handler: Function): void {
    this.handlers.get(type as string)?.delete(handler);
  }

  /** Register connect event handler */
  onConnect(handler: ConnectHandler): void {
    this.connectHandlers.add(handler);
  }

  /** Register disconnect event handler */
  onDisconnect(handler: DisconnectHandler): void {
    this.disconnectHandlers.add(handler);
  }

  /** Register error event handler */
  onError(handler: ErrorHandler): void {
    this.errorHandlers.add(handler);
  }

  private sendRaw(data: any): void {
    if (this.ws?.readyState === WebSocket.OPEN) {
      this.ws.send(JSON.stringify(data));
    }
  }

  private handleMessage(data: any): void {
    const type = data.type;
    if (!type) return;
    const handlers = this.handlers.get(type);
    if (handlers) {
      const msg = { ...data };
      delete msg.type;
      handlers.forEach((h) => h(msg));
    }
  }

  private tryReconnect(): void {
    if (this.options.maxReconnectAttempts > 0 &&
        this.reconnectAttempts >= this.options.maxReconnectAttempts) {
      return;
    }
    this.reconnectAttempts++;
    this.reconnectTimer = setTimeout(() => {
      this.connect().catch(() => {});
    }, this.options.reconnectInterval);
  }

  private startHeartbeat(): void {
    if (this.options.heartbeatInterval <= 0) return;
    this.heartbeatTimer = setInterval(() => {
      this.sendRaw({ type: "__ping__" });
    }, this.options.heartbeatInterval);
  }

  private stopHeartbeat(): void {
    if (this.heartbeatTimer) {
      clearInterval(this.heartbeatTimer);
      this.heartbeatTimer = null;
    }
  }
}
`
