package codegen

// tsProtoSDKTemplate 生成 TypeScript Protobuf SDK
// 基于 protobuf.js (Long 支持) + 零拷贝帧格式
// 生成内容：
//   1. 消息类型注册表 (TypeURL → Encoder/Decoder)
//   2. ProtobufAdapter 实现 Codec 接口，可注入 GameClient
//   3. 辅助函数：loadFromRoot / registerAll
const tsProtoSDKTemplate = `// Code generated by msggen. DO NOT EDIT.
// TypeScript Protobuf SDK — 配合服务端 remote/zero_copy.go 的 TypeURL 解码路径
//
// 用法：
//   import * as protobuf from "protobufjs";
//   import { ProtobufAdapter, registerAllMessages, TypeRegistry } from "./proto_sdk";
//
//   const root = await protobuf.load("messages.proto");
//   const registry = registerAllMessages(root);
//   const codec = new ProtobufAdapter(registry);
//   const client = new GameClient({ url, codec });

// ============================================================
// Protobuf Type Registry
// ============================================================

export interface ProtoType {
  encode(msg: unknown): { finish(): Uint8Array };
  decode(buf: Uint8Array): unknown;
  create?(props?: Record<string, unknown>): unknown;
  toObject?(msg: unknown, opts?: Record<string, unknown>): Record<string, unknown>;
}

export interface ProtoRoot {
  lookupType(typeName: string): ProtoType;
}

/** 消息 ID → 消息名 */
export const ProtoMessageIDs = {
{{- range .}}
  {{.Name}}: {{.ID}},
{{- end}}
} as const;

/** 消息名 → 消息 ID */
export const ProtoMessageNameToID: Record<string, number> = {
{{- range .}}
  "{{.Name}}": {{.ID}},
{{- end}}
};

/** 消息 ID → 消息名（反向） */
export const ProtoMessageIDToName: Record<number, string> = {
{{- range .}}
  {{.ID}}: "{{.Name}}",
{{- end}}
};

/** 所有消息名（用于批量注册） */
export const ProtoMessageList: readonly string[] = [
{{- range .}}
  "{{.Name}}",
{{- end}}
];

/**
 * TypeRegistry — TypeURL → Encoder/Decoder 映射
 * 与服务端 remote.TypeRegistry 保持一致的寻址方式
 */
export class TypeRegistry {
  private types = new Map<string, ProtoType>();

  /** 注册一个消息类型 */
  register(typeName: string, protoType: ProtoType): void {
    this.types.set(typeName, protoType);
  }

  /** 按 TypeURL (通常等同于消息名) 查找类型 */
  lookup(typeName: string): ProtoType | undefined {
    return this.types.get(typeName);
  }

  /** 已注册的类型名列表 */
  list(): string[] {
    return Array.from(this.types.keys());
  }

  /** 已注册类型数量 */
  size(): number {
    return this.types.size;
  }
}

/**
 * 从 protobuf.js 的 Root 自动注册所有消息类型
 * @param root  protobuf.js 的 Root 实例（通过 protobuf.load 加载）
 * @param pkg   可选的包名前缀，例如 "game."
 */
export function registerAllMessages(root: ProtoRoot, pkg: string = ""): TypeRegistry {
  const registry = new TypeRegistry();
  for (const name of ProtoMessageList) {
    const fullName = pkg ? pkg + name : name;
    try {
      const t = root.lookupType(fullName);
      registry.register(name, t);
    } catch {
      // 消息未在 proto 文件中定义，跳过
    }
  }
  return registry;
}

// ============================================================
// Protobuf Codec Adapter
// ============================================================

/**
 * ProtobufAdapter — 适配 GameClient 的 Codec 接口
 * 帧格式: [2字节大端 MessageID] [protobuf payload]
 */
export class ProtobufAdapter {
  private registry: TypeRegistry;

  constructor(registry: TypeRegistry) {
    this.registry = registry;
  }

  encode(type: string, msg: unknown): ArrayBuffer {
    const id = ProtoMessageNameToID[type];
    if (id === undefined) {
      throw new Error("unknown protobuf message type: " + type);
    }
    const pt = this.registry.lookup(type);
    if (!pt) {
      throw new Error("protobuf type not registered: " + type);
    }
    const payload = pt.encode(msg).finish();
    const frame = new Uint8Array(2 + payload.length);
    frame[0] = (id >> 8) & 0xff;
    frame[1] = id & 0xff;
    frame.set(payload, 2);
    return frame.buffer;
  }

  decode(data: ArrayBuffer | string): { type: string; payload: unknown } | null {
    if (typeof data === "string") return null;
    const buf = new Uint8Array(data);
    if (buf.length < 2) return null;
    const id = (buf[0] << 8) | buf[1];
    const typeName = ProtoMessageIDToName[id];
    if (!typeName) return null;
    const pt = this.registry.lookup(typeName);
    if (!pt) return null;
    const raw = pt.decode(buf.slice(2));
    const payload = pt.toObject ? pt.toObject(raw, { defaults: true, longs: Number }) : raw;
    return { type: typeName, payload };
  }
}

// ============================================================
// 消息接口（TypeScript 类型提示，仅开发期使用）
// 运行时消息实例由 protobuf.js 的 Message 类驱动
// ============================================================
{{- range .}}

/** {{.Comment}} */
export interface {{.Name}} {
{{- range .Fields}}
  {{.JSONName}}?: {{tsType .Type}};
{{- end}}
}
{{- end}}

export interface ProtoMessageMap {
{{- range .}}
  {{.Name}}: {{.Name}};
{{- end}}
}
`

// csharpProtoSDKTemplate 生成 C# Protobuf SDK
// 基于 Google.Protobuf 库 (protoc 生成的 IMessage 接口)
const csharpProtoSDKTemplate = `// Code generated by msggen. DO NOT EDIT.
// C# Protobuf SDK — 适配 Unity + Google.Protobuf
//
// 依赖：
//   - Google.Protobuf (NuGet)
//   - protoc 生成的 .cs 文件（使用与服务端相同的 .proto）
//
// 用法：
//   var registry = ProtoTypeRegistry.CreateDefault();
//   var codec = new ProtobufCodecAdapter(registry);
//   var client = new GameClient(url, CodecMode.Protobuf, registry);

using System;
using System.Collections.Generic;
using Google.Protobuf;

namespace {{.Namespace}}
{
    // ============================================================
    // Message ID Constants
    // ============================================================

    public static class ProtoMessageIDs
    {
{{- range .Messages}}
        public const ushort {{.Name}} = {{.ID}};
{{- end}}
    }

    // ============================================================
    // Type Registry — TypeURL → MessageParser 映射
    // ============================================================

    /// <summary>
    /// Protobuf 类型注册表，维护消息名 ↔ MessageID ↔ Parser 三元映射
    /// </summary>
    public class ProtoTypeRegistry
    {
        private readonly Dictionary<string, MessageParser> _parsers
            = new Dictionary<string, MessageParser>();
        private readonly Dictionary<ushort, string> _idToName
            = new Dictionary<ushort, string>();
        private readonly Dictionary<string, ushort> _nameToId
            = new Dictionary<string, ushort>();

        /// <summary>注册一个 protobuf 消息类型</summary>
        public void Register<T>(string name, ushort id, MessageParser<T> parser)
            where T : IMessage<T>
        {
            _parsers[name] = parser;
            _idToName[id] = name;
            _nameToId[name] = id;
        }

        /// <summary>注册一个 protobuf 消息类型（反射风格，接受非泛型 Parser）</summary>
        public void RegisterRaw(string name, ushort id, MessageParser parser)
        {
            _parsers[name] = parser;
            _idToName[id] = name;
            _nameToId[name] = id;
        }

        public MessageParser Lookup(string name)
        {
            return _parsers.TryGetValue(name, out var p) ? p : null;
        }

        public string NameOf(ushort id)
        {
            return _idToName.TryGetValue(id, out var n) ? n : null;
        }

        public ushort IdOf(string name)
        {
            return _nameToId.TryGetValue(name, out var id) ? id : (ushort)0;
        }

        public int Size => _parsers.Count;

        /// <summary>消息名集合（用于遍历已注册类型）</summary>
        public IEnumerable<string> Names => _parsers.Keys;

        /// <summary>
        /// 创建预声明所有 ID 的默认注册表
        /// 使用方应调用 Register&lt;T&gt;(name, id, parser) 绑定具体 Parser
        /// </summary>
        public static ProtoTypeRegistry CreateDefault()
        {
            var r = new ProtoTypeRegistry();
{{- range .Messages}}
            r._idToName[ProtoMessageIDs.{{.Name}}] = "{{.Name}}";
            r._nameToId["{{.Name}}"] = ProtoMessageIDs.{{.Name}};
{{- end}}
            return r;
        }
    }

    // ============================================================
    // Protobuf Codec Adapter
    // ============================================================

    /// <summary>
    /// Protobuf 编解码器，帧格式: [2字节大端 MessageID] [protobuf payload]
    /// </summary>
    public class ProtobufCodecAdapter
    {
        private readonly ProtoTypeRegistry _registry;

        public ProtobufCodecAdapter(ProtoTypeRegistry registry)
        {
            _registry = registry ?? throw new ArgumentNullException(nameof(registry));
        }

        public byte[] Encode(string type, IMessage msg)
        {
            if (msg == null) throw new ArgumentNullException(nameof(msg));
            ushort id = _registry.IdOf(type);
            if (id == 0) throw new InvalidOperationException("unknown message type: " + type);
            byte[] payload = msg.ToByteArray();
            byte[] frame = new byte[2 + payload.Length];
            frame[0] = (byte)((id >> 8) & 0xff);
            frame[1] = (byte)(id & 0xff);
            Array.Copy(payload, 0, frame, 2, payload.Length);
            return frame;
        }

        public (string Type, IMessage Payload)? Decode(byte[] data)
        {
            if (data == null || data.Length < 2) return null;
            ushort id = (ushort)((data[0] << 8) | data[1]);
            string typeName = _registry.NameOf(id);
            if (typeName == null) return null;
            var parser = _registry.Lookup(typeName);
            if (parser == null) return null;
            var payload = parser.ParseFrom(data, 2, data.Length - 2);
            return (typeName, payload);
        }
    }
}
`

// protoRegistryExampleTemplate 生成服务端消息类型注册示例
// 帮助用户将 TypeURL 与 protobuf 消息工厂绑定在一起
const protoRegistryExampleTemplate = `// Code generated by msggen. DO NOT EDIT.
// 服务端与客户端共享的消息 ID 常量（单一数据源）
package {{.Package}}

// ProtoMessageID 协议消息 ID 常量，与客户端 SDK 保持一致
const (
{{- range .Messages}}
	ProtoMsgID_{{.Name}} uint16 = {{.ID}}
{{- end}}
)

// ProtoMessageName 消息 ID → 名称的反向查找表
var ProtoMessageName = map[uint16]string{
{{- range .Messages}}
	ProtoMsgID_{{.Name}}: "{{.Name}}",
{{- end}}
}

// ProtoMessageID 消息名称 → ID 的正向查找表
var ProtoMessageID = map[string]uint16{
{{- range .Messages}}
	"{{.Name}}": ProtoMsgID_{{.Name}},
{{- end}}
}
`

// tsExampleMainTemplate 生成 TypeScript 示例工程的 main.ts
const tsExampleMainTemplate = `// TypeScript Protobuf SDK 示例入口
// 运行前：npm install protobufjs
//
// 1. 用 protobuf.load 加载 .proto 定义
// 2. 通过 registerAllMessages 批量注册到 TypeRegistry
// 3. 将 ProtobufAdapter 注入 GameClient 的 codec 参数

import * as protobuf from "protobufjs";
import { GameClient } from "./sdk";
import { ProtobufAdapter, registerAllMessages } from "./proto_sdk";

async function main() {
  // 加载与服务端相同的 .proto 文件
  const root = await protobuf.load("messages.proto");
  const registry = registerAllMessages(root);
  console.log("registered proto types:", registry.size());

  const codec = new ProtobufAdapter(registry);
  const client = new GameClient({
    url: "ws://localhost:8080/ws",
    codec,
  });

  client.router.onAny((type, msg) => {
    console.log("[recv]", type, msg);
  });

  await client.connect();
  console.log("connected, protocol =", client.protocolVersion);
}

main().catch(err => {
  console.error(err);
  process.exit(1);
});
`

// csharpRPCEnhancedTemplate 生成 C# 强类型 RPC / Push 增强层
// 与 tsRPCEnhancedTemplate 能力一致，提供：
//   - TypedRpcClient.CallAsync<TResp>(requestTypeName, request, parser, timeout) — Task + 超时 + 取消
//   - PushStream<T>：基于 Channel 的 IAsyncEnumerable<T>（OnPush<T> Unity 端等价物）
//   - RpcTimeoutException / RpcCanceledException
//
// 约定：请求载荷通过 __rpc_id 字段与响应配对，服务端需原样回传（与 TS 侧保持一致）
const csharpRPCEnhancedTemplate = `// Code generated by msggen. DO NOT EDIT.
// C# RPC & Push Enhancement — 强类型 RPC/Push 封装（Unity + .NET 6+ 通用）
//
// 依赖：Google.Protobuf (IMessage / MessageParser)；.NET Standard 2.1+/.NET 6+ 的 Channel 与 IAsyncEnumerable
// Unity: 建议使用 UniTask 替代 Task 以获得更好 Unity 主线程兼容性（接口签名一致）

using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Channels;
using System.Threading.Tasks;
using Google.Protobuf;

namespace {{.Namespace}}
{
    // ============================================================
    // RPC 传输接口：与 GameClient 相容的最小依赖
    // ============================================================

    /// <summary>RPC 需要的最小传输接口：发送 + 路由订阅</summary>
    public interface IRpcTransport
    {
        /// <summary>以消息类型名发送一个 protobuf 消息</summary>
        void Send(string typeName, IMessage payload);
        /// <summary>订阅指定消息类型的回调，返回取消订阅句柄</summary>
        IDisposable Subscribe(string typeName, Action<IMessage> handler);
    }

    // ============================================================
    // 异常类型
    // ============================================================

    public class RpcTimeoutException : Exception
    {
        public string RequestType { get; }
        public TimeSpan Timeout { get; }
        public RpcTimeoutException(string requestType, TimeSpan timeout)
            : base($"RPC timeout: {requestType} after {timeout.TotalMilliseconds}ms")
        {
            RequestType = requestType;
            Timeout = timeout;
        }
    }

    public class RpcCanceledException : OperationCanceledException
    {
        public string RequestType { get; }
        public RpcCanceledException(string requestType)
            : base($"RPC canceled: {requestType}")
        {
            RequestType = requestType;
        }
    }

    // ============================================================
    // TypedRpcClient — 强类型 RPC 封装
    // ============================================================

    /// <summary>
    /// TypedRpcClient 在 IRpcTransport 之上提供 Task 风格的 RPC 封装。
    ///
    /// 典型用法：
    ///   var rpc = new TypedRpcClient(client);
    ///   var resp = await rpc.CallAsync<LoginResponse>(
    ///       "LoginRequest", req, LoginResponse.Parser,
    ///       TimeSpan.FromSeconds(5), ct);
    ///
    /// 注意：依赖服务端在响应中回传与请求相同的 __rpc_id 字段；
    /// 若协议无此字段，将退化为匹配第一个到达的同类型响应。
    /// </summary>
    public sealed class TypedRpcClient : IDisposable
    {
        private readonly IRpcTransport _transport;
        private readonly Dictionary<string, IDisposable> _subscriptions = new Dictionary<string, IDisposable>();
        private readonly ConcurrentDictionary<long, PendingCall> _pending = new ConcurrentDictionary<long, PendingCall>();
        private long _seq;

        public TypedRpcClient(IRpcTransport transport)
        {
            _transport = transport ?? throw new ArgumentNullException(nameof(transport));
        }

        public Task<TResp> CallAsync<TResp>(
            string requestType,
            IMessage request,
            string responseType,
            MessageParser<TResp> responseParser,
            TimeSpan timeout,
            CancellationToken cancellationToken = default)
            where TResp : IMessage<TResp>
        {
            if (string.IsNullOrEmpty(requestType)) throw new ArgumentNullException(nameof(requestType));
            if (request == null) throw new ArgumentNullException(nameof(request));
            if (string.IsNullOrEmpty(responseType)) throw new ArgumentNullException(nameof(responseType));
            if (responseParser == null) throw new ArgumentNullException(nameof(responseParser));

            EnsureSubscribed(responseType);

            var tcs = new TaskCompletionSource<TResp>(TaskCreationOptions.RunContinuationsAsynchronously);
            var id = Interlocked.Increment(ref _seq);
            var entry = new PendingCall
            {
                Type = responseType,
                Settle = msg =>
                {
                    try
                    {
                        var typed = responseParser.ParseFrom(msg.ToByteString());
                        tcs.TrySetResult(typed);
                    }
                    catch (Exception ex) { tcs.TrySetException(ex); }
                },
                Fail = ex => tcs.TrySetException(ex),
            };

            CancellationTokenSource linked = null;
            if (timeout > TimeSpan.Zero)
            {
                linked = CancellationTokenSource.CreateLinkedTokenSource(cancellationToken);
                linked.CancelAfter(timeout);
                linked.Token.Register(() =>
                {
                    if (_pending.TryRemove(id, out _))
                    {
                        if (cancellationToken.IsCancellationRequested)
                            tcs.TrySetException(new RpcCanceledException(requestType));
                        else
                            tcs.TrySetException(new RpcTimeoutException(requestType, timeout));
                    }
                    linked?.Dispose();
                });
            }
            else if (cancellationToken.CanBeCanceled)
            {
                cancellationToken.Register(() =>
                {
                    if (_pending.TryRemove(id, out _))
                        tcs.TrySetException(new RpcCanceledException(requestType));
                });
            }

            _pending[id] = entry;
            // 将 __rpc_id 附加到协议层（要求服务端在响应中回传）
            // Protobuf 无扩展字段时可改用帧层 header；此处保留策略钩子
            _transport.Send(requestType, new TaggedMessage(request, id));
            return tcs.Task;
        }

        public void Dispose()
        {
            foreach (var kv in _pending)
                kv.Value.Fail(new ObjectDisposedException(nameof(TypedRpcClient)));
            _pending.Clear();
            foreach (var sub in _subscriptions.Values) sub.Dispose();
            _subscriptions.Clear();
        }

        private void EnsureSubscribed(string responseType)
        {
            lock (_subscriptions)
            {
                if (_subscriptions.ContainsKey(responseType)) return;
                var sub = _transport.Subscribe(responseType, msg =>
                {
                    // 约定 message 可能是 TaggedMessage 包裹，或直接是 IMessage
                    long? rpcId = TaggedMessage.TryGetId(msg);
                    if (rpcId.HasValue && _pending.TryRemove(rpcId.Value, out var entry))
                    {
                        entry.Settle(TaggedMessage.Unwrap(msg));
                        return;
                    }
                    // 降级：匹配首个相同类型的未决请求
                    foreach (var kv in _pending)
                    {
                        if (kv.Value.Type == responseType && _pending.TryRemove(kv.Key, out var hit))
                        {
                            hit.Settle(TaggedMessage.Unwrap(msg));
                            return;
                        }
                    }
                });
                _subscriptions[responseType] = sub;
            }
        }

        private class PendingCall
        {
            public string Type;
            public Action<IMessage> Settle;
            public Action<Exception> Fail;
        }
    }

    /// <summary>
    /// TaggedMessage 为请求附带 __rpc_id。
    /// 实际序列化时由 transport 决定如何承载该字段（最简单做法：写入帧头额外 8 字节）。
    /// </summary>
    public sealed class TaggedMessage : IMessage
    {
        public IMessage Inner { get; }
        public long RpcId { get; }
        public TaggedMessage(IMessage inner, long rpcId) { Inner = inner; RpcId = rpcId; }

        public static long? TryGetId(IMessage msg) => (msg as TaggedMessage)?.RpcId;
        public static IMessage Unwrap(IMessage msg) => (msg as TaggedMessage)?.Inner ?? msg;

        public MessageDescriptor Descriptor => Inner.Descriptor;
        public int CalculateSize() => Inner.CalculateSize();
        public void MergeFrom(CodedInputStream input) => Inner.MergeFrom(input);
        public void WriteTo(CodedOutputStream output) => Inner.WriteTo(output);
    }

    // ============================================================
    // PushStream<T> — 基于 Channel 的 IAsyncEnumerable
    // 等价于 TS 的 OnPush<T>，Unity 中建议用 UniTask 版本的 Channel
    // ============================================================

    /// <summary>
    /// PushStream 将路由事件转换为可用 await foreach 消费的异步流。
    /// 使用完成后务必 Dispose 以退订 router 订阅。
    /// </summary>
    public sealed class PushStream<T> : IAsyncEnumerable<T>, IDisposable
        where T : IMessage<T>
    {
        private readonly Channel<T> _channel;
        private readonly IDisposable _subscription;
        private volatile bool _disposed;

        public PushStream(IRpcTransport transport, string typeName,
            MessageParser<T> parser, int capacity = 64, bool dropOldest = true)
        {
            var opts = new BoundedChannelOptions(capacity)
            {
                FullMode = dropOldest ? BoundedChannelFullMode.DropOldest : BoundedChannelFullMode.Wait,
                SingleReader = true,
                SingleWriter = true,
            };
            _channel = Channel.CreateBounded<T>(opts);

            _subscription = transport.Subscribe(typeName, msg =>
            {
                try
                {
                    var raw = TaggedMessage.Unwrap(msg);
                    // 若 raw 已经是目标类型则直接使用，否则按字节重新解析
                    if (raw is T typed) _channel.Writer.TryWrite(typed);
                    else _channel.Writer.TryWrite(parser.ParseFrom(raw.ToByteString()));
                }
                catch { /* 静默丢弃解析失败的消息 */ }
            });
        }

        public void Dispose()
        {
            if (_disposed) return;
            _disposed = true;
            _subscription?.Dispose();
            _channel.Writer.TryComplete();
        }

        public async IAsyncEnumerator<T> GetAsyncEnumerator(CancellationToken ct = default)
        {
            while (await _channel.Reader.WaitToReadAsync(ct).ConfigureAwait(false))
            {
                while (_channel.Reader.TryRead(out var item))
                    yield return item;
            }
        }
    }

    // ============================================================
    // TypedPushSubscriber — 常用单条等待 / 回调订阅
    // ============================================================

    public sealed class TypedPushSubscriber
    {
        private readonly IRpcTransport _transport;
        public TypedPushSubscriber(IRpcTransport transport) { _transport = transport; }

        /// <summary>回调风格订阅，返回 IDisposable 控制生命周期</summary>
        public IDisposable On<T>(string typeName, MessageParser<T> parser, Action<T> handler)
            where T : IMessage<T>
        {
            return _transport.Subscribe(typeName, msg =>
            {
                var raw = TaggedMessage.Unwrap(msg);
                var typed = raw is T already ? already : parser.ParseFrom(raw.ToByteString());
                handler(typed);
            });
        }

        /// <summary>等待单条消息（Task 风格）</summary>
        public Task<T> OnceAsync<T>(string typeName, MessageParser<T> parser,
            TimeSpan timeout, CancellationToken ct = default)
            where T : IMessage<T>
        {
            var tcs = new TaskCompletionSource<T>(TaskCreationOptions.RunContinuationsAsynchronously);
            IDisposable sub = null;
            sub = On<T>(typeName, parser, msg =>
            {
                tcs.TrySetResult(msg);
                sub?.Dispose();
            });
            if (timeout > TimeSpan.Zero)
            {
                var cts = CancellationTokenSource.CreateLinkedTokenSource(ct);
                cts.CancelAfter(timeout);
                cts.Token.Register(() =>
                {
                    if (tcs.TrySetException(new RpcTimeoutException(typeName, timeout)))
                        sub?.Dispose();
                });
            }
            else if (ct.CanBeCanceled)
            {
                ct.Register(() =>
                {
                    if (tcs.TrySetException(new RpcCanceledException(typeName)))
                        sub?.Dispose();
                });
            }
            return tcs.Task;
        }

        /// <summary>创建一个 PushStream 异步流</summary>
        public PushStream<T> OnPush<T>(string typeName, MessageParser<T> parser,
            int capacity = 64, bool dropOldest = true)
            where T : IMessage<T>
        {
            return new PushStream<T>(_transport, typeName, parser, capacity, dropOldest);
        }
    }
}
`

// tsRPCEnhancedTemplate 生成 TypeScript 强类型 RPC / Push 增强层
//
// 提供三项核心能力：
//   1. RPC 风格 API：`call<K>(type, req, opts?)` 根据 Request → Response 命名约定自动推导返回类型
//   2. Promise + 超时封装：请求超时后自动 reject，避免处理器漏注册导致的永久挂起
//   3. 事件订阅器 OnPush<T>：提供 on / once / asyncIterator 三种消费方式，AbortSignal 友好
//
// 约定：
//   - 消息命名形如 `XxxRequest` 与 `XxxResponse` 被识别为 RPC 对，其余保留为单向 push
//   - 运行时必须提供一个实现了 `send(type, msg)` 与 `router.on(type, handler)` 的客户端
//     （与 sdk.ts / sdk_v2 中的 GameClient 接口一致）
//   - 需要服务端在响应中透传 `request_id`（或使用帧级别 seq 字段），此模板采用消息帧内约定：
//     请求发送前会将 `__rpc_id` 注入到对象上；服务端应在响应中原样回传该字段
const tsRPCEnhancedTemplate = `// Code generated by msggen. DO NOT EDIT.
// TypeScript RPC & Push Enhancement — 基于生成的 MessageMap 提供强类型封装
//
// 要求：
//   - 运行时需要一个实现了以下最小接口的客户端实例：
//       interface RPCTransport {
//         send(type: string, msg: unknown): void;
//         router: { on(type: string, handler: (msg: unknown) => void): () => void };
//       }
//   - 服务端应支持 __rpc_id 透传：收到含 __rpc_id 字段的请求后，响应中原样回传
//   - 未支持 __rpc_id 的服务端降级：按 Response 类型匹配第一条到达的响应，可能与并发请求冲突

// ============================================================
// RPC Map — Request → Response 类型对
// 基于命名约定（XxxRequest → XxxResponse）自动识别
// ============================================================

export interface RPCMap {
{{- range .Pairs}}
  {{.Request}}: "{{.Response}}";
{{- end}}
}

/** RPC 请求类型集合 */
export type RPCRequestType = keyof RPCMap;

/** 根据请求类型推导响应类型名 */
export type RPCResponseType<K extends RPCRequestType> = RPCMap[K];

// ============================================================
// RPC Client — 强类型 call<K>(type, req)
// ============================================================

/** RPC 调用选项 */
export interface RPCCallOptions {
  /** 超时毫秒数，0 = 不超时（默认 5000） */
  timeoutMs?: number;
  /** 可选的外部 AbortSignal，触发后立即 reject */
  signal?: AbortSignal;
}

/** RPC 超时错误（可通过 name 判别） */
export class RPCTimeoutError extends Error {
  readonly name = "RPCTimeoutError";
  constructor(public readonly requestType: string, public readonly timeoutMs: number) {
    super("RPC timeout: " + requestType + " after " + timeoutMs + "ms");
  }
}

/** RPC 取消错误（signal 触发） */
export class RPCAbortError extends Error {
  readonly name = "RPCAbortError";
  constructor(public readonly requestType: string) {
    super("RPC aborted: " + requestType);
  }
}

/** 最小的 RPC 传输接口，与 GameClient 相容 */
export interface RPCTransport {
  send(type: string, msg: unknown): void;
  router: {
    on(type: string, handler: (msg: unknown) => void): () => void;
  };
}

interface PendingCall {
  resolve: (msg: unknown) => void;
  reject: (err: Error) => void;
  timer: ReturnType<typeof setTimeout> | null;
  cleanup: () => void;
}

/**
 * RPCClient — 基于 MessageMap 的强类型 RPC 封装
 *
 * 用法:
 *   const rpc = new RPCClient(gameClient);
 *   const resp = await rpc.call("LoginRequest", { username: "x", password: "y" });
 *   // resp 被推导为 LoginResponse
 */
export class RPCClient {
  private seq = 0;
  private pending = new Map<number, PendingCall>();
  private unsubs: Array<() => void> = [];
  private installed = new Set<string>();

  constructor(private readonly client: RPCTransport) {}

  call<K extends RPCRequestType>(
    type: K,
    req: MessageMap[K],
    opts: RPCCallOptions = {}
  ): Promise<MessageMap[RPCResponseType<K>]> {
    const respType = RPCPairs[type as string];
    if (!respType) {
      return Promise.reject(new Error("not an RPC request: " + (type as string)));
    }
    this.ensureSubscribed(respType);
    return new Promise((resolve, reject) => {
      const id = ++this.seq;
      const timeoutMs = opts.timeoutMs ?? 5000;

      const cleanup = () => {
        const p = this.pending.get(id);
        if (!p) return;
        if (p.timer) clearTimeout(p.timer);
        this.pending.delete(id);
      };

      const entry: PendingCall = {
        resolve: (m) => { cleanup(); resolve(m as MessageMap[RPCResponseType<K>]); },
        reject:  (e) => { cleanup(); reject(e); },
        timer: null,
        cleanup,
      };

      if (timeoutMs > 0) {
        entry.timer = setTimeout(() => {
          entry.reject(new RPCTimeoutError(type as string, timeoutMs));
        }, timeoutMs);
      }
      if (opts.signal) {
        if (opts.signal.aborted) {
          entry.reject(new RPCAbortError(type as string));
          return;
        }
        opts.signal.addEventListener("abort", () => {
          entry.reject(new RPCAbortError(type as string));
        }, { once: true });
      }

      this.pending.set(id, entry);
      // 将 __rpc_id 注入请求（服务端须回传）
      const payload: unknown = { ...(req as object), __rpc_id: id };
      try {
        this.client.send(type as string, payload);
      } catch (err) {
        entry.reject(err instanceof Error ? err : new Error(String(err)));
      }
    });
  }

  /** 释放所有订阅与待决请求（调用后 RPCClient 不再可用） */
  dispose(): void {
    this.pending.forEach(p => p.reject(new Error("RPCClient disposed")));
    this.pending.clear();
    this.unsubs.forEach(fn => fn());
    this.unsubs.length = 0;
    this.installed.clear();
  }

  /** 懒订阅指定响应类型，同一类型只订阅一次 */
  private ensureSubscribed(respType: string): void {
    if (this.installed.has(respType)) return;
    this.installed.add(respType);
    const off = this.client.router.on(respType, (msg: unknown) => {
      const rpcId = (msg as { __rpc_id?: number })?.__rpc_id;
      if (typeof rpcId === "number") {
        const p = this.pending.get(rpcId);
        if (p) { p.resolve(msg); return; }
      }
      // 降级：取最早的未决调用（服务端未回传 __rpc_id）
      for (const [id, p] of this.pending) {
        this.pending.delete(id);
        p.resolve(msg);
        return;
      }
    });
    this.unsubs.push(off);
  }
}

/** RPC Request → Response 映射（供 RPCClient 内部路由使用） */
const RPCPairs: Readonly<Record<string, string>> = {
{{- range .Pairs}}
  "{{.Request}}": "{{.Response}}",
{{- end}}
};

// ============================================================
// Push Subscriber — 强类型 OnPush<T>
// 提供 on / once / asyncIterator / toPromise 四种消费方式
// ============================================================

/** Push 订阅配置 */
export interface PushOptions {
  /** AbortSignal — 触发后自动退订并结束 asyncIterator */
  signal?: AbortSignal;
  /** 最多接收多少条后自动退订，默认不限 */
  limit?: number;
}

/** Push 订阅句柄 */
export interface PushSubscription<T> {
  /** 手动退订 */
  unsubscribe(): void;
  /** 将订阅转换为 async iterator，for-await-of 消费 */
  [Symbol.asyncIterator](): AsyncIterator<T>;
  /** 获取下一条消息（Promise），并在之后自动退订 */
  next(): Promise<T>;
}

/**
 * PushSubscriber — 基于 MessageMap 的强类型事件订阅器
 *
 * 用法:
 *   const push = new PushSubscriber(gameClient);
 *   // 1) 传统回调
 *   const sub = push.on("ScoreUpdateNotify", msg => ui.setScore(msg.score));
 *   sub.unsubscribe();
 *
 *   // 2) async iterator
 *   for await (const msg of push.onPush("LeaderboardNotify", { signal: ac.signal })) {
 *     renderLeaderboard(msg.entries);
 *   }
 *
 *   // 3) one-shot
 *   const first = await push.once("GameStartNotify");
 */
export class PushSubscriber {
  constructor(private readonly client: RPCTransport) {}

  /** 回调风格订阅（返回退订句柄） */
  on<K extends keyof MessageMap>(
    type: K,
    handler: (msg: MessageMap[K]) => void
  ): { unsubscribe(): void } {
    const off = this.client.router.on(type as string, (msg: unknown) => {
      handler(msg as MessageMap[K]);
    });
    return { unsubscribe: off };
  }

  /** 等待单条消息（Promise） */
  once<K extends keyof MessageMap>(
    type: K,
    opts: PushOptions = {}
  ): Promise<MessageMap[K]> {
    return new Promise((resolve, reject) => {
      let settled = false;
      const off = this.client.router.on(type as string, (msg: unknown) => {
        if (settled) return;
        settled = true;
        off();
        resolve(msg as MessageMap[K]);
      });
      if (opts.signal) {
        if (opts.signal.aborted) {
          settled = true;
          off();
          reject(new RPCAbortError(type as string));
          return;
        }
        opts.signal.addEventListener("abort", () => {
          if (settled) return;
          settled = true;
          off();
          reject(new RPCAbortError(type as string));
        }, { once: true });
      }
    });
  }

  /** async iterator 风格订阅 */
  onPush<K extends keyof MessageMap>(
    type: K,
    opts: PushOptions = {}
  ): PushSubscription<MessageMap[K]> {
    const self = this;
    const buffer: MessageMap[K][] = [];
    const waiters: Array<(v: IteratorResult<MessageMap[K]>) => void> = [];
    let received = 0;
    let done = false;

    const finish = () => {
      if (done) return;
      done = true;
      off();
      while (waiters.length) {
        const w = waiters.shift()!;
        w({ value: undefined as unknown as MessageMap[K], done: true });
      }
    };

    const off = this.client.router.on(type as string, (msg: unknown) => {
      if (done) return;
      if (waiters.length) {
        waiters.shift()!({ value: msg as MessageMap[K], done: false });
      } else {
        buffer.push(msg as MessageMap[K]);
      }
      received++;
      if (opts.limit && received >= opts.limit) finish();
    });

    if (opts.signal) {
      if (opts.signal.aborted) finish();
      else opts.signal.addEventListener("abort", finish, { once: true });
    }

    return {
      unsubscribe: finish,
      [Symbol.asyncIterator](): AsyncIterator<MessageMap[K]> {
        return {
          next(): Promise<IteratorResult<MessageMap[K]>> {
            if (buffer.length) {
              return Promise.resolve({ value: buffer.shift()!, done: false });
            }
            if (done) {
              return Promise.resolve({
                value: undefined as unknown as MessageMap[K], done: true,
              });
            }
            return new Promise<IteratorResult<MessageMap[K]>>(r => waiters.push(r));
          },
          return(): Promise<IteratorResult<MessageMap[K]>> {
            finish();
            return Promise.resolve({
              value: undefined as unknown as MessageMap[K], done: true,
            });
          },
        };
      },
      next(): Promise<MessageMap[K]> {
        return self.once(type, opts);
      },
    };
  }
}

// ============================================================
// 集成入口：基于 GameClient 创建 RPC + Push
// ============================================================

export function createRPC(client: RPCTransport): RPCClient {
  return new RPCClient(client);
}

export function createPush(client: RPCTransport): PushSubscriber {
  return new PushSubscriber(client);
}
`

// unityProtoExampleTemplate 生成 Unity C# 示例 MonoBehaviour
const unityProtoExampleTemplate = `// Unity 示例：Protobuf 客户端接入
// 前置条件：
//   1. 使用 protoc 根据服务端 .proto 生成 C# 类
//   2. 导入 Google.Protobuf DLL 至 Unity 工程
//   3. 将 GameClient.cs + ProtoTypeRegistry.cs 挂载到此对象

using System.Collections;
using UnityEngine;

namespace {{.Namespace}}.Example
{
    public class ProtobufClientExample : MonoBehaviour
    {
        [SerializeField] private string serverUrl = "ws://127.0.0.1:8080/ws";

        private IEnumerator Start()
        {
            // Step 1: 创建注册表（预声明所有 MessageID）
            var registry = ProtoTypeRegistry.CreateDefault();

            // Step 2: 绑定每个消息类型的 Parser（protoc 生成的 Parser 静态字段）
            // 示例（实际代码按你的消息类名调用 Register）：
            //   registry.Register<LoginRequest>(nameof(LoginRequest),
            //       ProtoMessageIDs.LoginRequest, LoginRequest.Parser);

            // Step 3: 注入到 GameClient（见 GameClient.cs 的 CodecMode.Protobuf 分支）
            Debug.Log($"[ProtoExample] registry size = {registry.Size}");

            yield return null;
        }
    }
}
`
