package codegen

// tsSDKEnhancedTemplate 增强版 TypeScript SDK 模板
// 新增: 消息路由分发器（替代 switch-case）+ Protobuf 编解码支持
const tsSDKEnhancedTemplate = `// Code generated by msggen. DO NOT EDIT.
// Enhanced TypeScript SDK — Message Router + Protobuf Support

// ============================================================
// Message Interfaces
// ============================================================
{{- range .}}

/** {{.Comment}} */
export interface {{.Name}} {
{{- range .Fields}}
  {{.JSONName}}: {{tsType .Type}};
{{- end}}
}
{{- end}}

// ============================================================
// Message IDs & Names
// ============================================================

export const MessageIDs = {
{{- range .}}
  {{.Name}}: {{.ID}},
{{- end}}
} as const;

export type MessageType = keyof typeof MessageIDs;

const MessageNames: Record<number, string> = {
{{- range .}}
  {{.ID}}: "{{.Name}}",
{{- end}}
};

// ============================================================
// Type-Safe Message Map
// ============================================================

export interface MessageMap {
{{- range .}}
  {{.Name}}: {{.Name}};
{{- end}}
}

// ============================================================
// Codec Interface — JSON / Protobuf 双模式
// ============================================================

export interface Codec {
  encode(type: string, msg: any): ArrayBuffer | string;
  decode(data: ArrayBuffer | string): { type: string; payload: any } | null;
}

/** JSON 编解码器（默认） */
export class JSONCodec implements Codec {
  encode(type: string, msg: any): string {
    return JSON.stringify({ type, ...msg });
  }

  decode(data: ArrayBuffer | string): { type: string; payload: any } | null {
    try {
      const text = typeof data === "string" ? data : new TextDecoder().decode(data);
      const obj = JSON.parse(text);
      const type = obj.type;
      if (!type) return null;
      const payload = { ...obj };
      delete payload.type;
      return { type, payload };
    } catch {
      return null;
    }
  }
}

/**
 * Protobuf 编解码器
 * 需要传入 protobuf.js 的 Root 实例和消息名→proto类型的映射
 * 消息帧格式: [2字节消息ID][protobuf数据]
 */
export class ProtobufCodec implements Codec {
  private typeMap: Map<string, { encode: (msg: any) => Uint8Array; decode: (buf: Uint8Array) => any }>;
  private idToName: Record<number, string>;
  private nameToId: Record<string, number>;

  constructor(
    typeMap: Map<string, { encode: (msg: any) => Uint8Array; decode: (buf: Uint8Array) => any }>,
    nameToId: Record<string, number>
  ) {
    this.typeMap = typeMap;
    this.nameToId = nameToId;
    this.idToName = {};
    for (const [name, id] of Object.entries(nameToId)) {
      this.idToName[id] = name;
    }
  }

  encode(type: string, msg: any): ArrayBuffer {
    const id = this.nameToId[type];
    if (id === undefined) throw new Error("unknown message type: " + type);
    const protoType = this.typeMap.get(type);
    if (!protoType) throw new Error("no proto type registered: " + type);

    const payload = protoType.encode(msg);
    // 帧: [2字节大端消息ID] [protobuf payload]
    const frame = new Uint8Array(2 + payload.length);
    frame[0] = (id >> 8) & 0xff;
    frame[1] = id & 0xff;
    frame.set(payload, 2);
    return frame.buffer;
  }

  decode(data: ArrayBuffer | string): { type: string; payload: any } | null {
    if (typeof data === "string") return null; // protobuf 需要二进制
    const buf = new Uint8Array(data);
    if (buf.length < 2) return null;

    const id = (buf[0] << 8) | buf[1];
    const typeName = this.idToName[id];
    if (!typeName) return null;

    const protoType = this.typeMap.get(typeName);
    if (!protoType) return null;

    const payload = protoType.decode(buf.slice(2));
    return { type: typeName, payload };
  }
}

// ============================================================
// Message Router — 类型安全的消息分发器（替代 switch-case）
// ============================================================

export type MessageHandler<T> = (msg: T) => void;

/**
 * 消息路由分发器
 *
 * 用法:
 *   const router = new MessageRouter();
 *   router.on("LoginResponse", (msg) => console.log(msg.token));
 *   router.on("ChatMessage", (msg) => showChat(msg.content));
 *   // 在收到消息时:
 *   router.dispatch("LoginResponse", data);
 */
export class MessageRouter {
  private handlers = new Map<string, Set<Function>>();
  private wildcardHandlers = new Set<(type: string, msg: any) => void>();

  /** 注册某消息类型的处理器（类型安全） */
  on<K extends keyof MessageMap>(type: K, handler: MessageHandler<MessageMap[K]>): () => void {
    if (!this.handlers.has(type as string)) {
      this.handlers.set(type as string, new Set());
    }
    this.handlers.get(type as string)!.add(handler);
    return () => this.off(type, handler);
  }

  /** 注册通配处理器，接收所有消息 */
  onAny(handler: (type: string, msg: any) => void): () => void {
    this.wildcardHandlers.add(handler);
    return () => this.wildcardHandlers.delete(handler);
  }

  /** 移除某消息类型的处理器 */
  off<K extends keyof MessageMap>(type: K, handler: Function): void {
    this.handlers.get(type as string)?.delete(handler);
  }

  /** 移除某消息类型的所有处理器 */
  offAll<K extends keyof MessageMap>(type: K): void {
    this.handlers.delete(type as string);
  }

  /** 分发消息到已注册的处理器，返回是否有处理器匹配 */
  dispatch(type: string, msg: any): boolean {
    let handled = false;
    const handlers = this.handlers.get(type);
    if (handlers && handlers.size > 0) {
      handlers.forEach((h) => h(msg));
      handled = true;
    }
    if (this.wildcardHandlers.size > 0) {
      this.wildcardHandlers.forEach((h) => h(type, msg));
      handled = true;
    }
    return handled;
  }

  /** 清空所有处理器 */
  clear(): void {
    this.handlers.clear();
    this.wildcardHandlers.clear();
  }
}

// ============================================================
// Client Options & Events
// ============================================================

export interface ClientOptions {
  /** WebSocket server URL, e.g. "ws://localhost:8080/ws" */
  url: string;
  /** Enable auto-reconnect (default: true) */
  reconnect?: boolean;
  /** Reconnect interval in ms (default: 3000) */
  reconnectInterval?: number;
  /** Max reconnect attempts, 0 = unlimited (default: 10) */
  maxReconnectAttempts?: number;
  /** Heartbeat ping interval in ms, 0 = disabled (default: 30000) */
  heartbeatInterval?: number;
  /** Protocol version for handshake (default: 1) */
  protocolVersion?: number;
  /** Codec to use, defaults to JSONCodec */
  codec?: Codec;
}

export type ConnectionState = "disconnected" | "connecting" | "connected" | "reconnecting";
export type ConnectHandler = () => void;
export type DisconnectHandler = (code: number, reason: string) => void;
export type ErrorHandler = (error: Event | Error) => void;
export type StateChangeHandler = (state: ConnectionState) => void;

// ============================================================
// Game Client SDK (Enhanced)
// ============================================================

const PROTOCOL_VERSION = 1;
const SDK_VERSION = "2.0.0";

export class GameClient {
  private ws: WebSocket | null = null;
  private connectHandlers = new Set<ConnectHandler>();
  private disconnectHandlers = new Set<DisconnectHandler>();
  private errorHandlers = new Set<ErrorHandler>();
  private stateChangeHandlers = new Set<StateChangeHandler>();
  private options: Required<Omit<ClientOptions, "codec">> & { codec: Codec };
  private reconnectAttempts = 0;
  private reconnectTimer: ReturnType<typeof setTimeout> | null = null;
  private heartbeatTimer: ReturnType<typeof setInterval> | null = null;
  private closed = false;
  private negotiatedVersion = PROTOCOL_VERSION;
  private _state: ConnectionState = "disconnected";

  /** 消息路由器 — 注册消息处理器（替代手动 switch-case） */
  public readonly router = new MessageRouter();

  constructor(options: ClientOptions) {
    this.options = {
      url: options.url,
      reconnect: options.reconnect ?? true,
      reconnectInterval: options.reconnectInterval ?? 3000,
      maxReconnectAttempts: options.maxReconnectAttempts ?? 10,
      heartbeatInterval: options.heartbeatInterval ?? 30000,
      protocolVersion: options.protocolVersion ?? PROTOCOL_VERSION,
      codec: options.codec ?? new JSONCodec(),
    };
  }

  /** 当前连接状态 */
  get state(): ConnectionState {
    return this._state;
  }

  /** 是否已连接 */
  get connected(): boolean {
    return this._state === "connected";
  }

  /** 协商后的协议版本 */
  get protocolVersion(): number {
    return this.negotiatedVersion;
  }

  /** Connect to the server with handshake */
  connect(): Promise<void> {
    this.closed = false;
    this.setState("connecting");
    return new Promise((resolve, reject) => {
      try {
        this.ws = new WebSocket(this.options.url);
        if (this.options.codec instanceof ProtobufCodec) {
          this.ws.binaryType = "arraybuffer";
        }
      } catch (err) {
        this.setState("disconnected");
        reject(err);
        return;
      }

      this.ws.onopen = () => {
        this.reconnectAttempts = 0;
        this.startHeartbeat();
        // Send handshake as JSON regardless of codec
        const hs = JSON.stringify({
          type: "__handshake__",
          protocol_version: this.options.protocolVersion,
          client_sdk: "ts-" + SDK_VERSION,
          supported_versions: [1],
        });
        this.ws!.send(hs);
      };

      this.ws.onmessage = (event: MessageEvent) => {
        // Handshake response is always JSON
        if (typeof event.data === "string" && event.data.includes("__handshake_ack__")) {
          try {
            const data = JSON.parse(event.data);
            if (data.status === "ok") {
              this.negotiatedVersion = data.protocol_version ?? PROTOCOL_VERSION;
              this.setState("connected");
              this.connectHandlers.forEach((h) => h());
              resolve();
            } else {
              reject(new Error(data.message ?? "handshake failed"));
            }
          } catch {
            reject(new Error("invalid handshake response"));
          }
          return;
        }

        // Decode message with configured codec
        const decoded = this.options.codec.decode(event.data);
        if (decoded) {
          this.router.dispatch(decoded.type, decoded.payload);
        }
      };

      this.ws.onerror = (event: Event) => {
        this.errorHandlers.forEach((h) => h(event));
        reject(event);
      };

      this.ws.onclose = (event: CloseEvent) => {
        this.stopHeartbeat();
        this.disconnectHandlers.forEach((h) => h(event.code, event.reason));
        if (!this.closed && this.options.reconnect) {
          this.tryReconnect();
        } else {
          this.setState("disconnected");
        }
      };
    });
  }

  /** Disconnect from the server */
  disconnect(): void {
    this.closed = true;
    this.stopHeartbeat();
    if (this.reconnectTimer) {
      clearTimeout(this.reconnectTimer);
      this.reconnectTimer = null;
    }
    if (this.ws) {
      this.ws.close(1000, "client disconnect");
      this.ws = null;
    }
    this.setState("disconnected");
  }

  /** Send a typed message */
  send<K extends keyof MessageMap>(type: K, msg: MessageMap[K]): void {
    if (!this.ws || this.ws.readyState !== WebSocket.OPEN) return;
    const encoded = this.options.codec.encode(type as string, msg);
    this.ws.send(encoded);
  }

  /** Register connect event handler */
  onConnect(handler: ConnectHandler): () => void {
    this.connectHandlers.add(handler);
    return () => this.connectHandlers.delete(handler);
  }

  /** Register disconnect event handler */
  onDisconnect(handler: DisconnectHandler): () => void {
    this.disconnectHandlers.add(handler);
    return () => this.disconnectHandlers.delete(handler);
  }

  /** Register error event handler */
  onError(handler: ErrorHandler): () => void {
    this.errorHandlers.add(handler);
    return () => this.errorHandlers.delete(handler);
  }

  /** Register state change handler */
  onStateChange(handler: StateChangeHandler): () => void {
    this.stateChangeHandlers.add(handler);
    return () => this.stateChangeHandlers.delete(handler);
  }

  private setState(state: ConnectionState): void {
    if (this._state === state) return;
    this._state = state;
    this.stateChangeHandlers.forEach((h) => h(state));
  }

  private tryReconnect(): void {
    if (this.options.maxReconnectAttempts > 0 &&
        this.reconnectAttempts >= this.options.maxReconnectAttempts) {
      this.setState("disconnected");
      return;
    }
    this.reconnectAttempts++;
    this.setState("reconnecting");
    this.reconnectTimer = setTimeout(() => {
      this.connect().catch(() => {});
    }, this.options.reconnectInterval);
  }

  private startHeartbeat(): void {
    if (this.options.heartbeatInterval <= 0) return;
    this.heartbeatTimer = setInterval(() => {
      if (this.ws?.readyState === WebSocket.OPEN) {
        this.ws.send(JSON.stringify({ type: "__ping__" }));
      }
    }, this.options.heartbeatInterval);
  }

  private stopHeartbeat(): void {
    if (this.heartbeatTimer) {
      clearInterval(this.heartbeatTimer);
      this.heartbeatTimer = null;
    }
  }
}
`
