package codegen

const markdownDocTemplate = `# Message API Reference

> Auto-generated by msggen. DO NOT EDIT.

## Overview

| Message | ID | Description |
|---------|-----|-------------|
{{- range .}}
| {{.Name}} | {{.ID}} | {{.Comment}} |
{{- end}}

---
{{range .}}
## {{.Name}}

**Message ID:** ` + "`{{.ID}}`" + `

{{.Comment}}

| Field | Type | JSON Key | JSON Type | Description |
|-------|------|----------|-----------|-------------|
{{- range .Fields}}
| {{.Name}} | ` + "`{{.Type}}`" + ` | {{.JSONName}} | {{jsonType .Type}} | {{.Comment}} |
{{- end}}

---
{{end}}`
