package codegen

const csharpTemplate = `// Code generated by msggen. DO NOT EDIT.

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace {{.Namespace}}
{
    /// <summary>消息 ID 常量</summary>
    public static class MessageIDs
    {
{{- range .Messages}}
        public const ushort {{.Name}} = {{.ID}};
{{- end}}
    }
{{range .Messages}}
    /// <summary>{{.Comment}}</summary>
    [Serializable]
    public class {{.Name}}
    {
        [JsonProperty("type")]
        public string Type => "{{.Name}}";
{{range .Fields}}
        /// <summary>{{.Comment}}</summary>
        [JsonProperty("{{.JSONName}}")]
        public {{csType .Type}} {{.Name}} { get; set; }
{{end}}    }
{{end}}
    /// <summary>消息工厂 — 根据 type 字段反序列化为具体消息类型</summary>
    public static class MessageFactory
    {
        private static readonly Dictionary<string, Type> TypeMap = new Dictionary<string, Type>
        {
{{- range .Messages}}
            { "{{.Name}}", typeof({{.Name}}) },
{{- end}}
        };

        /// <summary>反序列化 JSON 为对应的消息对象</summary>
        public static object Deserialize(string json)
        {
            var obj = JObject.Parse(json);
            var typeName = obj["type"]?.ToString();
            if (typeName != null && TypeMap.TryGetValue(typeName, out var type))
            {
                return JsonConvert.DeserializeObject(json, type);
            }
            return null;
        }

        /// <summary>序列化消息对象为 JSON</summary>
        public static string Serialize(object msg)
        {
            return JsonConvert.SerializeObject(msg);
        }
    }
}
`
