package codegen

// csharpSDKTemplate 生成完整的 C# 客户端 SDK（含 TCP/WebSocket 连接管理、自动重连、消息路由）
// 适配 Unity 工程，可直接导入
const csharpSDKTemplate = `// Code generated by msggen. DO NOT EDIT.
// Unity Client SDK — TCP/WebSocket connection + auto-reconnect + message routing

using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Net.Sockets;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace {{.Namespace}}
{
    // ============================================================
    // Message Definitions
    // ============================================================

    public static class MessageIDs
    {
{{- range .Messages}}
        public const ushort {{.Name}} = {{.ID}};
{{- end}}
    }
{{range .Messages}}
    /// <summary>{{.Comment}}</summary>
    [Serializable]
    public class {{.Name}}
    {
        [JsonProperty("type")]
        public string Type => "{{.Name}}";
{{range .Fields}}
        [JsonProperty("{{.JSONName}}")]
        public {{csType .Type}} {{.Name}} { get; set; }
{{end}}    }
{{end}}

    // ============================================================
    // Network State
    // ============================================================

    /// <summary>网络连接状态</summary>
    public enum ConnectionState
    {
        Disconnected,
        Connecting,
        Connected,
        Reconnecting
    }

    /// <summary>编解码模式</summary>
    public enum CodecMode
    {
        JSON,
        Protobuf
    }

    // ============================================================
    // Message Router — 按消息类型自动分发
    // ============================================================

    /// <summary>消息处理器委托</summary>
    public delegate void MessageHandler<in T>(T message);

    /// <summary>
    /// 消息路由分发器 — 注册处理器，按消息类型自动分发
    /// </summary>
    public class MessageRouter
    {
        private readonly Dictionary<string, List<Action<object>>> _handlers
            = new Dictionary<string, List<Action<object>>>();

        /// <summary>注册某消息类型的处理器</summary>
        public void Register<T>(MessageHandler<T> handler) where T : class
        {
            var typeName = typeof(T).Name;
            if (!_handlers.ContainsKey(typeName))
                _handlers[typeName] = new List<Action<object>>();
            _handlers[typeName].Add(obj => handler(obj as T));
        }

        /// <summary>移除某消息类型的所有处理器</summary>
        public void Unregister<T>() where T : class
        {
            _handlers.Remove(typeof(T).Name);
        }

        /// <summary>分发消息到已注册的处理器</summary>
        public bool Dispatch(string typeName, object message)
        {
            if (!_handlers.TryGetValue(typeName, out var list))
                return false;
            foreach (var h in list)
                h(message);
            return true;
        }
    }

    // ============================================================
    // Message Factory — JSON/Protobuf 双模式反序列化
    // ============================================================

    public static class MessageFactory
    {
        private static readonly Dictionary<string, Type> TypeMap = new Dictionary<string, Type>
        {
{{- range .Messages}}
            { "{{.Name}}", typeof({{.Name}}) },
{{- end}}
        };

        public static object Deserialize(string json)
        {
            var obj = JObject.Parse(json);
            var typeName = obj["type"]?.ToString();
            if (typeName != null && TypeMap.TryGetValue(typeName, out var type))
                return JsonConvert.DeserializeObject(json, type);
            return null;
        }

        public static string Serialize(object msg)
        {
            return JsonConvert.SerializeObject(msg);
        }

        public static bool TryGetTypeName(string json, out string typeName)
        {
            try
            {
                var obj = JObject.Parse(json);
                typeName = obj["type"]?.ToString();
                return typeName != null;
            }
            catch
            {
                typeName = null;
                return false;
            }
        }
    }

    // ============================================================
    // Client Options
    // ============================================================

    /// <summary>客户端连接配置</summary>
    public class ClientOptions
    {
        /// <summary>服务器地址 (host:port 或 ws://host:port/path)</summary>
        public string Address { get; set; }

        /// <summary>传输协议: "tcp" 或 "websocket"</summary>
        public string Transport { get; set; } = "websocket";

        /// <summary>编解码模式</summary>
        public CodecMode Codec { get; set; } = CodecMode.JSON;

        /// <summary>是否启用自动重连 (默认 true)</summary>
        public bool AutoReconnect { get; set; } = true;

        /// <summary>重连间隔毫秒 (默认 3000)</summary>
        public int ReconnectIntervalMs { get; set; } = 3000;

        /// <summary>最大重连次数, 0=无限 (默认 10)</summary>
        public int MaxReconnectAttempts { get; set; } = 10;

        /// <summary>心跳间隔毫秒, 0=禁用 (默认 30000)</summary>
        public int HeartbeatIntervalMs { get; set; } = 30000;

        /// <summary>协议版本号 (默认 1)</summary>
        public int ProtocolVersion { get; set; } = 1;
    }

    // ============================================================
    // GameClient — 游戏客户端 SDK 主类
    // ============================================================

    /// <summary>
    /// 游戏客户端 SDK — 支持 TCP/WebSocket、自动重连、消息路由分发
    /// <para>典型用法：</para>
    /// <code>
    /// var client = new GameClient(new ClientOptions { Address = "ws://localhost:8080/ws" });
    /// client.Router.Register&lt;LoginResponse&gt;(msg => Debug.Log("Login OK: " + msg.Token));
    /// client.OnConnected += () => client.Send(new LoginRequest { Username = "test" });
    /// await client.ConnectAsync();
    /// </code>
    /// </summary>
    public class GameClient : IDisposable
    {
        private readonly ClientOptions _options;
        private TcpClient _tcpClient;
        private NetworkStream _stream;
        private CancellationTokenSource _cts;
        private int _reconnectAttempts;
        private volatile bool _disposed;

        /// <summary>消息路由器 — 注册消息处理器</summary>
        public MessageRouter Router { get; } = new MessageRouter();

        /// <summary>当前连接状态</summary>
        public ConnectionState State { get; private set; } = ConnectionState.Disconnected;

        /// <summary>协商后的协议版本</summary>
        public int NegotiatedVersion { get; private set; }

        // --- 事件回调 ---

        /// <summary>连接成功时触发</summary>
        public event Action OnConnected;

        /// <summary>连接断开时触发 (参数: 原因)</summary>
        public event Action<string> OnDisconnected;

        /// <summary>正在重连时触发 (参数: 第几次尝试)</summary>
        public event Action<int> OnReconnecting;

        /// <summary>发生错误时触发</summary>
        public event Action<Exception> OnError;

        public GameClient(ClientOptions options)
        {
            _options = options ?? throw new ArgumentNullException(nameof(options));
        }

        /// <summary>异步连接到服务器</summary>
        public async Task ConnectAsync()
        {
            if (_disposed) throw new ObjectDisposedException(nameof(GameClient));

            State = ConnectionState.Connecting;
            _cts = new CancellationTokenSource();
            _reconnectAttempts = 0;

            try
            {
                await DoConnectAsync();
            }
            catch (Exception ex)
            {
                State = ConnectionState.Disconnected;
                OnError?.Invoke(ex);
                throw;
            }
        }

        /// <summary>断开连接</summary>
        public void Disconnect()
        {
            _cts?.Cancel();
            CloseConnection("client disconnect");
            State = ConnectionState.Disconnected;
        }

        /// <summary>发送消息对象</summary>
        public void Send(object message)
        {
            if (State != ConnectionState.Connected)
                throw new InvalidOperationException("not connected");

            var json = MessageFactory.Serialize(message);
            SendRaw(json);
        }

        /// <summary>发送原始 JSON 字符串</summary>
        public void SendRaw(string json)
        {
            if (_stream == null || !_stream.CanWrite) return;

            var data = Encoding.UTF8.GetBytes(json);
            // 长度前缀帧: 4字节大端长度 + 数据
            var frame = new byte[4 + data.Length];
            frame[0] = (byte)(data.Length >> 24);
            frame[1] = (byte)(data.Length >> 16);
            frame[2] = (byte)(data.Length >> 8);
            frame[3] = (byte)(data.Length);
            Buffer.BlockCopy(data, 0, frame, 4, data.Length);

            try
            {
                _stream.Write(frame, 0, frame.Length);
            }
            catch (Exception ex)
            {
                OnError?.Invoke(ex);
                HandleDisconnect("write error: " + ex.Message);
            }
        }

        public void Dispose()
        {
            if (_disposed) return;
            _disposed = true;
            Disconnect();
            _tcpClient?.Dispose();
        }

        // --- 内部实现 ---

        private async Task DoConnectAsync()
        {
            // TCP 连接
            var parts = _options.Address.Replace("tcp://", "").Split(':');
            var host = parts[0];
            var port = parts.Length > 1 ? int.Parse(parts[1]) : 8080;

            _tcpClient = new TcpClient();
            await _tcpClient.ConnectAsync(host, port);
            _stream = _tcpClient.GetStream();
            _tcpClient.NoDelay = true;

            // 发送握手
            var handshake = JsonConvert.SerializeObject(new
            {
                type = "__handshake__",
                protocol_version = _options.ProtocolVersion,
                client_sdk = "csharp-1.0.0"
            });
            SendRaw(handshake);

            // 等待握手响应
            var response = await ReadMessageAsync(_cts.Token);
            if (response != null)
            {
                var obj = JObject.Parse(response);
                if (obj["type"]?.ToString() == "__handshake_ack__")
                {
                    if (obj["status"]?.ToString() != "ok")
                        throw new Exception("handshake failed: " + obj["message"]?.ToString());
                    NegotiatedVersion = obj["protocol_version"]?.ToObject<int>() ?? _options.ProtocolVersion;
                }
            }

            State = ConnectionState.Connected;
            _reconnectAttempts = 0;
            OnConnected?.Invoke();

            // 启动读取循环和心跳
            _ = Task.Run(() => ReadLoopAsync(_cts.Token));
            if (_options.HeartbeatIntervalMs > 0)
                _ = Task.Run(() => HeartbeatLoopAsync(_cts.Token));
        }

        private async Task ReadLoopAsync(CancellationToken ct)
        {
            try
            {
                while (!ct.IsCancellationRequested)
                {
                    var msg = await ReadMessageAsync(ct);
                    if (msg == null)
                    {
                        HandleDisconnect("connection closed by server");
                        return;
                    }

                    // 分发消息
                    if (MessageFactory.TryGetTypeName(msg, out var typeName))
                    {
                        var deserialized = MessageFactory.Deserialize(msg);
                        if (deserialized != null)
                            Router.Dispatch(typeName, deserialized);
                    }
                }
            }
            catch (OperationCanceledException) { }
            catch (Exception ex)
            {
                OnError?.Invoke(ex);
                HandleDisconnect("read error: " + ex.Message);
            }
        }

        private async Task<string> ReadMessageAsync(CancellationToken ct)
        {
            // 读取 4 字节长度前缀
            var lenBuf = new byte[4];
            var read = 0;
            while (read < 4)
            {
                var n = await _stream.ReadAsync(lenBuf, read, 4 - read, ct);
                if (n == 0) return null;
                read += n;
            }

            var length = (lenBuf[0] << 24) | (lenBuf[1] << 16) | (lenBuf[2] << 8) | lenBuf[3];
            if (length <= 0 || length > 10 * 1024 * 1024) return null; // 10MB 上限

            var dataBuf = new byte[length];
            read = 0;
            while (read < length)
            {
                var n = await _stream.ReadAsync(dataBuf, read, length - read, ct);
                if (n == 0) return null;
                read += n;
            }

            return Encoding.UTF8.GetString(dataBuf);
        }

        private async Task HeartbeatLoopAsync(CancellationToken ct)
        {
            try
            {
                while (!ct.IsCancellationRequested)
                {
                    await Task.Delay(_options.HeartbeatIntervalMs, ct);
                    if (State == ConnectionState.Connected)
                        SendRaw("{\"type\":\"__ping__\"}");
                }
            }
            catch (OperationCanceledException) { }
        }

        private void HandleDisconnect(string reason)
        {
            CloseConnection(reason);

            if (!_disposed && _options.AutoReconnect)
            {
                _ = TryReconnectAsync();
            }
        }

        private async Task TryReconnectAsync()
        {
            while (!_disposed && (_options.MaxReconnectAttempts == 0 ||
                   _reconnectAttempts < _options.MaxReconnectAttempts))
            {
                _reconnectAttempts++;
                State = ConnectionState.Reconnecting;
                OnReconnecting?.Invoke(_reconnectAttempts);

                try
                {
                    await Task.Delay(_options.ReconnectIntervalMs);
                    _cts = new CancellationTokenSource();
                    await DoConnectAsync();
                    return; // 重连成功
                }
                catch (Exception ex)
                {
                    OnError?.Invoke(ex);
                }
            }

            State = ConnectionState.Disconnected;
            OnDisconnected?.Invoke("max reconnect attempts reached");
        }

        private void CloseConnection(string reason)
        {
            var wasConnected = State == ConnectionState.Connected;
            try
            {
                _stream?.Close();
                _tcpClient?.Close();
            }
            catch { }
            _stream = null;
            _tcpClient = null;

            if (wasConnected)
            {
                State = ConnectionState.Disconnected;
                OnDisconnected?.Invoke(reason);
            }
        }
    }
}
`
