package codegen

const goTemplate = `// Code generated by msggen. DO NOT EDIT.
package {{.Package}}

// 消息 ID 常量
const (
{{- range .Messages}}
	MsgID_{{.Name}} uint16 = {{.ID}}
{{- end}}
)

// MessageTypes 消息类型工厂映射
var MessageTypes = map[uint16]func() interface{}{
{{- range .Messages}}
	MsgID_{{.Name}}: func() interface{} { return &{{.Name}}{} },
{{- end}}
}

// RegisterMessages 注册所有消息到路由器
// router 需实现 Register(msg interface{}, handler interface{}) 方法
func RegisterMessages(router interface{ Register(msg interface{}, handler interface{}) }) {
{{- range .Messages}}
	router.Register(&{{.Name}}{}, nil)
{{- end}}
}

// GetMessageByID 根据消息 ID 创建消息实例
func GetMessageByID(id uint16) interface{} {
	if factory, ok := MessageTypes[id]; ok {
		return factory()
	}
	return nil
}
`

const tsTemplate = `// Code generated by msggen. DO NOT EDIT.

{{- range .}}

/** {{.Comment}} */
export interface {{.Name}} {
{{- range .Fields}}
  {{.Name}}: {{tsType .Type}};
{{- end}}
}
{{- end}}

export const MessageIDs = {
{{- range .}}
  {{.Name}}: {{.ID}},
{{- end}}
} as const;
`

const typeRegistryTemplate = `// Code generated by msggen. DO NOT EDIT.
package {{.Package}}

import "engine/remote"

// RegisterProtoTypes 将所有 Proto 消息类型注册到 TypeRegistry
func RegisterProtoTypes(registry *remote.TypeRegistry) {
{{- range .Messages}}
	registry.RegisterName("{{.Name}}", &{{.Name}}{})
{{- end}}
}
`
