package codegen

// tsProtoSDKTemplate 生成 TypeScript Protobuf SDK
// 基于 protobuf.js (Long 支持) + 零拷贝帧格式
// 生成内容：
//   1. 消息类型注册表 (TypeURL → Encoder/Decoder)
//   2. ProtobufAdapter 实现 Codec 接口，可注入 GameClient
//   3. 辅助函数：loadFromRoot / registerAll
const tsProtoSDKTemplate = `// Code generated by msggen. DO NOT EDIT.
// TypeScript Protobuf SDK — 配合服务端 remote/zero_copy.go 的 TypeURL 解码路径
//
// 用法：
//   import * as protobuf from "protobufjs";
//   import { ProtobufAdapter, registerAllMessages, TypeRegistry } from "./proto_sdk";
//
//   const root = await protobuf.load("messages.proto");
//   const registry = registerAllMessages(root);
//   const codec = new ProtobufAdapter(registry);
//   const client = new GameClient({ url, codec });

// ============================================================
// Protobuf Type Registry
// ============================================================

export interface ProtoType {
  encode(msg: unknown): { finish(): Uint8Array };
  decode(buf: Uint8Array): unknown;
  create?(props?: Record<string, unknown>): unknown;
  toObject?(msg: unknown, opts?: Record<string, unknown>): Record<string, unknown>;
}

export interface ProtoRoot {
  lookupType(typeName: string): ProtoType;
}

/** 消息 ID → 消息名 */
export const ProtoMessageIDs = {
{{- range .}}
  {{.Name}}: {{.ID}},
{{- end}}
} as const;

/** 消息名 → 消息 ID */
export const ProtoMessageNameToID: Record<string, number> = {
{{- range .}}
  "{{.Name}}": {{.ID}},
{{- end}}
};

/** 消息 ID → 消息名（反向） */
export const ProtoMessageIDToName: Record<number, string> = {
{{- range .}}
  {{.ID}}: "{{.Name}}",
{{- end}}
};

/** 所有消息名（用于批量注册） */
export const ProtoMessageList: readonly string[] = [
{{- range .}}
  "{{.Name}}",
{{- end}}
];

/**
 * TypeRegistry — TypeURL → Encoder/Decoder 映射
 * 与服务端 remote.TypeRegistry 保持一致的寻址方式
 */
export class TypeRegistry {
  private types = new Map<string, ProtoType>();

  /** 注册一个消息类型 */
  register(typeName: string, protoType: ProtoType): void {
    this.types.set(typeName, protoType);
  }

  /** 按 TypeURL (通常等同于消息名) 查找类型 */
  lookup(typeName: string): ProtoType | undefined {
    return this.types.get(typeName);
  }

  /** 已注册的类型名列表 */
  list(): string[] {
    return Array.from(this.types.keys());
  }

  /** 已注册类型数量 */
  size(): number {
    return this.types.size;
  }
}

/**
 * 从 protobuf.js 的 Root 自动注册所有消息类型
 * @param root  protobuf.js 的 Root 实例（通过 protobuf.load 加载）
 * @param pkg   可选的包名前缀，例如 "game."
 */
export function registerAllMessages(root: ProtoRoot, pkg: string = ""): TypeRegistry {
  const registry = new TypeRegistry();
  for (const name of ProtoMessageList) {
    const fullName = pkg ? pkg + name : name;
    try {
      const t = root.lookupType(fullName);
      registry.register(name, t);
    } catch {
      // 消息未在 proto 文件中定义，跳过
    }
  }
  return registry;
}

// ============================================================
// Protobuf Codec Adapter
// ============================================================

/**
 * ProtobufAdapter — 适配 GameClient 的 Codec 接口
 * 帧格式: [2字节大端 MessageID] [protobuf payload]
 */
export class ProtobufAdapter {
  private registry: TypeRegistry;

  constructor(registry: TypeRegistry) {
    this.registry = registry;
  }

  encode(type: string, msg: unknown): ArrayBuffer {
    const id = ProtoMessageNameToID[type];
    if (id === undefined) {
      throw new Error("unknown protobuf message type: " + type);
    }
    const pt = this.registry.lookup(type);
    if (!pt) {
      throw new Error("protobuf type not registered: " + type);
    }
    const payload = pt.encode(msg).finish();
    const frame = new Uint8Array(2 + payload.length);
    frame[0] = (id >> 8) & 0xff;
    frame[1] = id & 0xff;
    frame.set(payload, 2);
    return frame.buffer;
  }

  decode(data: ArrayBuffer | string): { type: string; payload: unknown } | null {
    if (typeof data === "string") return null;
    const buf = new Uint8Array(data);
    if (buf.length < 2) return null;
    const id = (buf[0] << 8) | buf[1];
    const typeName = ProtoMessageIDToName[id];
    if (!typeName) return null;
    const pt = this.registry.lookup(typeName);
    if (!pt) return null;
    const raw = pt.decode(buf.slice(2));
    const payload = pt.toObject ? pt.toObject(raw, { defaults: true, longs: Number }) : raw;
    return { type: typeName, payload };
  }
}

// ============================================================
// 消息接口（TypeScript 类型提示，仅开发期使用）
// 运行时消息实例由 protobuf.js 的 Message 类驱动
// ============================================================
{{- range .}}

/** {{.Comment}} */
export interface {{.Name}} {
{{- range .Fields}}
  {{.JSONName}}?: {{tsType .Type}};
{{- end}}
}
{{- end}}

export interface ProtoMessageMap {
{{- range .}}
  {{.Name}}: {{.Name}};
{{- end}}
}
`

// csharpProtoSDKTemplate 生成 C# Protobuf SDK
// 基于 Google.Protobuf 库 (protoc 生成的 IMessage 接口)
const csharpProtoSDKTemplate = `// Code generated by msggen. DO NOT EDIT.
// C# Protobuf SDK — 适配 Unity + Google.Protobuf
//
// 依赖：
//   - Google.Protobuf (NuGet)
//   - protoc 生成的 .cs 文件（使用与服务端相同的 .proto）
//
// 用法：
//   var registry = ProtoTypeRegistry.CreateDefault();
//   var codec = new ProtobufCodecAdapter(registry);
//   var client = new GameClient(url, CodecMode.Protobuf, registry);

using System;
using System.Collections.Generic;
using Google.Protobuf;

namespace {{.Namespace}}
{
    // ============================================================
    // Message ID Constants
    // ============================================================

    public static class ProtoMessageIDs
    {
{{- range .Messages}}
        public const ushort {{.Name}} = {{.ID}};
{{- end}}
    }

    // ============================================================
    // Type Registry — TypeURL → MessageParser 映射
    // ============================================================

    /// <summary>
    /// Protobuf 类型注册表，维护消息名 ↔ MessageID ↔ Parser 三元映射
    /// </summary>
    public class ProtoTypeRegistry
    {
        private readonly Dictionary<string, MessageParser> _parsers
            = new Dictionary<string, MessageParser>();
        private readonly Dictionary<ushort, string> _idToName
            = new Dictionary<ushort, string>();
        private readonly Dictionary<string, ushort> _nameToId
            = new Dictionary<string, ushort>();

        /// <summary>注册一个 protobuf 消息类型</summary>
        public void Register<T>(string name, ushort id, MessageParser<T> parser)
            where T : IMessage<T>
        {
            _parsers[name] = parser;
            _idToName[id] = name;
            _nameToId[name] = id;
        }

        /// <summary>注册一个 protobuf 消息类型（反射风格，接受非泛型 Parser）</summary>
        public void RegisterRaw(string name, ushort id, MessageParser parser)
        {
            _parsers[name] = parser;
            _idToName[id] = name;
            _nameToId[name] = id;
        }

        public MessageParser Lookup(string name)
        {
            return _parsers.TryGetValue(name, out var p) ? p : null;
        }

        public string NameOf(ushort id)
        {
            return _idToName.TryGetValue(id, out var n) ? n : null;
        }

        public ushort IdOf(string name)
        {
            return _nameToId.TryGetValue(name, out var id) ? id : (ushort)0;
        }

        public int Size => _parsers.Count;

        /// <summary>消息名集合（用于遍历已注册类型）</summary>
        public IEnumerable<string> Names => _parsers.Keys;

        /// <summary>
        /// 创建预声明所有 ID 的默认注册表
        /// 使用方应调用 Register&lt;T&gt;(name, id, parser) 绑定具体 Parser
        /// </summary>
        public static ProtoTypeRegistry CreateDefault()
        {
            var r = new ProtoTypeRegistry();
{{- range .Messages}}
            r._idToName[ProtoMessageIDs.{{.Name}}] = "{{.Name}}";
            r._nameToId["{{.Name}}"] = ProtoMessageIDs.{{.Name}};
{{- end}}
            return r;
        }
    }

    // ============================================================
    // Protobuf Codec Adapter
    // ============================================================

    /// <summary>
    /// Protobuf 编解码器，帧格式: [2字节大端 MessageID] [protobuf payload]
    /// </summary>
    public class ProtobufCodecAdapter
    {
        private readonly ProtoTypeRegistry _registry;

        public ProtobufCodecAdapter(ProtoTypeRegistry registry)
        {
            _registry = registry ?? throw new ArgumentNullException(nameof(registry));
        }

        public byte[] Encode(string type, IMessage msg)
        {
            if (msg == null) throw new ArgumentNullException(nameof(msg));
            ushort id = _registry.IdOf(type);
            if (id == 0) throw new InvalidOperationException("unknown message type: " + type);
            byte[] payload = msg.ToByteArray();
            byte[] frame = new byte[2 + payload.Length];
            frame[0] = (byte)((id >> 8) & 0xff);
            frame[1] = (byte)(id & 0xff);
            Array.Copy(payload, 0, frame, 2, payload.Length);
            return frame;
        }

        public (string Type, IMessage Payload)? Decode(byte[] data)
        {
            if (data == null || data.Length < 2) return null;
            ushort id = (ushort)((data[0] << 8) | data[1]);
            string typeName = _registry.NameOf(id);
            if (typeName == null) return null;
            var parser = _registry.Lookup(typeName);
            if (parser == null) return null;
            var payload = parser.ParseFrom(data, 2, data.Length - 2);
            return (typeName, payload);
        }
    }
}
`

// protoRegistryExampleTemplate 生成服务端消息类型注册示例
// 帮助用户将 TypeURL 与 protobuf 消息工厂绑定在一起
const protoRegistryExampleTemplate = `// Code generated by msggen. DO NOT EDIT.
// 服务端与客户端共享的消息 ID 常量（单一数据源）
package {{.Package}}

// ProtoMessageID 协议消息 ID 常量，与客户端 SDK 保持一致
const (
{{- range .Messages}}
	ProtoMsgID_{{.Name}} uint16 = {{.ID}}
{{- end}}
)

// ProtoMessageName 消息 ID → 名称的反向查找表
var ProtoMessageName = map[uint16]string{
{{- range .Messages}}
	ProtoMsgID_{{.Name}}: "{{.Name}}",
{{- end}}
}

// ProtoMessageID 消息名称 → ID 的正向查找表
var ProtoMessageID = map[string]uint16{
{{- range .Messages}}
	"{{.Name}}": ProtoMsgID_{{.Name}},
{{- end}}
}
`

// tsExampleMainTemplate 生成 TypeScript 示例工程的 main.ts
const tsExampleMainTemplate = `// TypeScript Protobuf SDK 示例入口
// 运行前：npm install protobufjs
//
// 1. 用 protobuf.load 加载 .proto 定义
// 2. 通过 registerAllMessages 批量注册到 TypeRegistry
// 3. 将 ProtobufAdapter 注入 GameClient 的 codec 参数

import * as protobuf from "protobufjs";
import { GameClient } from "./sdk";
import { ProtobufAdapter, registerAllMessages } from "./proto_sdk";

async function main() {
  // 加载与服务端相同的 .proto 文件
  const root = await protobuf.load("messages.proto");
  const registry = registerAllMessages(root);
  console.log("registered proto types:", registry.size());

  const codec = new ProtobufAdapter(registry);
  const client = new GameClient({
    url: "ws://localhost:8080/ws",
    codec,
  });

  client.router.onAny((type, msg) => {
    console.log("[recv]", type, msg);
  });

  await client.connect();
  console.log("connected, protocol =", client.protocolVersion);
}

main().catch(err => {
  console.error(err);
  process.exit(1);
});
`

// unityProtoExampleTemplate 生成 Unity C# 示例 MonoBehaviour
const unityProtoExampleTemplate = `// Unity 示例：Protobuf 客户端接入
// 前置条件：
//   1. 使用 protoc 根据服务端 .proto 生成 C# 类
//   2. 导入 Google.Protobuf DLL 至 Unity 工程
//   3. 将 GameClient.cs + ProtoTypeRegistry.cs 挂载到此对象

using System.Collections;
using UnityEngine;

namespace {{.Namespace}}.Example
{
    public class ProtobufClientExample : MonoBehaviour
    {
        [SerializeField] private string serverUrl = "ws://127.0.0.1:8080/ws";

        private IEnumerator Start()
        {
            // Step 1: 创建注册表（预声明所有 MessageID）
            var registry = ProtoTypeRegistry.CreateDefault();

            // Step 2: 绑定每个消息类型的 Parser（protoc 生成的 Parser 静态字段）
            // 示例（实际代码按你的消息类名调用 Register）：
            //   registry.Register<LoginRequest>(nameof(LoginRequest),
            //       ProtoMessageIDs.LoginRequest, LoginRequest.Parser);

            // Step 3: 注入到 GameClient（见 GameClient.cs 的 CodecMode.Protobuf 分支）
            Debug.Log($"[ProtoExample] registry size = {registry.Size}");

            yield return null;
        }
    }
}
`
