apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-engine
  labels:
    app.kubernetes.io/name: engine
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: helm
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: engine
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: gate
      port: {{ .Values.service.gatePort }}
      targetPort: gate
      protocol: TCP
    - name: ws
      port: {{ .Values.service.wsPort }}
      targetPort: ws
      protocol: TCP
    - name: dashboard
      port: {{ .Values.service.dashboardPort }}
      targetPort: dashboard
      protocol: TCP
    - name: gossip
      port: {{ .Values.service.gossipPort }}
      targetPort: gossip
      protocol: TCP
